name: Android-CI

on:
  pull_request:
    branches: [ "master" ]


jobs:
  run-tests:
    name: Run unit test on PR in master
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        name:
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Run unit tests
        run: ./gradlew test


