name: Android-CI

on:
  push:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:


jobs:
  run-tests:
    name: Build
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        name: Set up JDK
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle


      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Chmod gradlew
        run: chmod +x ./gradlew

      - name: Run unit tests
        run: ./gradlew --no-daemon build



