name: Android-CI

on:
  pull_request:
    branches: [ "master" ]


jobs:
  run-tests:
    name: Run unit test on PR in master
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        name: Set up JDK
        with:
          java-version: '11'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Run unit tests
        run: ./gradlew --no-daemon build



