name: Prepare release version


on:
  push:
    branches: [ "test-merge-branch" ]


jobs:
  Release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - uses: actions/setup-java@v3
        name: Set up JDK
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - uses: actions/cache@v2
        name: Caching gradle
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build Release
        run: |
          ./gradlew build
          ./gradlew assembleRelease --stacktrace

      - name: Sign apk
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "30.0.2"

      - name: Publish to dev server
        uses: fjogeleit/http-request-action@v1
        id: publish_to_server
        with:
          url: https://${{ secrets.CI_SERVER_DOMAIN_NAME }}/android/upload-apk?access_token=${{ secrets.CI_SERVER_ACCESS_TOKEN }}
          method: POST
          file: ${{ steps.sign_app.signedReleaseFile }}

      - name: Show http response
        run: |
          echo: ${{ fromJson(steps.publish_to_server.outputs.response).url }}
