name: Prepare release version


on:
  push:
    branches: [ "test-master" ]


jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Publish to dev server
        uses: JantHsueh/upload-file-action@master
        id: publish
        with:
          url: https://${{ secrets.CI_SERVER_DOMAIN_NAME }}/android/upload-apk?access_token=${{ secrets.CI_SERVER_ACCESS_TOKEN }}&version=${{ steps.previoustag.outputs.tag }}
          forms: '{}'
          fileForms: '{ "file": ".gitignore" }'

      - name: Send changelog via telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            Вышла новая версия приложения: ${{ steps.previoustag.outputs.tag }}
            
            Изменения:
            ${{ github.event.head_commit.message }}
            
            Ссылка на apk файл: ${{ fromJson(steps.publish.outputs.output).data.url }}


          

