name: Test

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [ "master" ]


jobs:
  run-tests:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        name: Set up JDK
        if: ${{ !contains( github.event.pull_request.labels.*.name, 'skip') }}
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Create local.properties file
        if: ${{ !contains( github.event.pull_request.labels.*.name, 'skip') }}
        run: |
          touch local.properties

          echo "keystore.password=${{ secrets.KEY_STORE_PASSWORD }}" >> local.properties
          echo "key.alias=${{ secrets.ALIAS }}" >> local.properties
          echo "key.password=${{ secrets.KEY_PASSWORD }}" >> local.properties

      - uses: actions/cache@v2
        if: ${{ !contains( github.event.pull_request.labels.*.name, 'skip') }}
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}

      - name: Grant execute permission for gradlew
        if: ${{ !contains( github.event.pull_request.labels.*.name, 'skip') }}
        run: chmod +x ./gradlew

      - name: Run tests
        if: ${{ !contains( github.event.pull_request.labels.*.name, 'skip') }}
        run: ./gradlew test

