name: Publish release version


on:
  push:
    tags:
      - '*'

jobs:
  publish-release:
    name: Publish release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - name: Exit if not on master branch
        if: endsWith(github.ref, 'test-master') == false
        run: exit -1

      - uses: actions/setup-java@v3
        name: Set up JDK
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle


      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew


      - name: Create local.properties file
        run: |
          touch local.properties
          
          echo "keystore.password=${{ secrets.KEY_STORE_PASSWORD }}" >> local.properties
          echo "key.alias=${{ secrets.ALIAS }}" >> local.properties
          echo "key.password=${{ secrets.KEY_PASSWORD }}" >> local.properties 

      - uses: actions/cache@v2
        name: Caching gradle
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build Release
        run: |
          ./gradlew assembleRelease --stacktrace

      - name: Get previous tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: v0.0.1

      - name: Publish to dev server
        uses: JantHsueh/upload-file-action@master
        id: publish
        with:
          url: https://${{ secrets.CI_SERVER_DOMAIN_NAME }}/android/upload-apk?access_token=${{ secrets.CI_SERVER_ACCESS_TOKEN }}&version=${{ steps.previoustag.outputs.tag }}
          forms: '{}'
          fileForms: '{ "file": "app/build/outputs/apk/release/app-release.apk" }'

      - name: Send changelog via telegram
        uses: appleboy/telegram-action@master


        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            Вышла новая версия приложения: ${{ steps.previoustag.outputs.tag }}
            
            Изменения:
            ${{ github.event.head_commit.message }}
            
            Ссылка на apk файл: ${{ fromJson(steps.publish.outputs.output).data.url }}
